### ISSUE TITLE
CentOS 8 EOL

### ISSUE THREAD

**Issue by Klaas-** [Azure/azhpc-images#110]
Hi,
currently the centos 8 hpc images are based on a product that will be gone in 2-3 months (as in no longer receive any updates). Are you planning to move to 8 stream? Or an different rhel derivate (rocky/alma/whatever)?

Greetings
Klaas

**Comment by tbugfinder** [comment]
Unfortunately there wasn't any update.
Are there any plans to move on to another RHEL based distribution ?

**Comment by tbugfinder** [comment]
`az vm image list --sku="gen"" --all --output table` lists an almalinux option.

I guess it is not built based on azhpc-images....
https://almalinux.org/tr/blog/almalinux-for-azure-hpc-now-available/

**Comment by jithinjosepkl** [comment]
We will be pushing out a refresh for the existing CentOS HPC images, but we are not considering to add a new HPC image (eg: 8.3 HPC). 

@tbugfinder - yes the Almalinux HPC image was built using the azhpc-images repro.

**Comment by tbugfinder** [comment]
Does this also mean that pre-built Rocky-HPC images won't appear any soon?
