### ISSUE TITLE
AZHPC CentOS 8.3 Image - release date

### ISSUE THREAD

**Issue by eliottkespi** [Azure/azhpc-images#118]
Hi,

From the Github repo, I can see that code has been written to support CentOS 8.3, but I can't find the image in the Azure Marketplace.
Can you please share when are you planning to release CentOS 8.3 image ?

Thanks,
Eliott

**Comment by jithinjosepkl** [comment]
@eliottkespi - thanks for checking, we are not planning to push out a CentOS 8.3 HPC image, given the CentOS EOL.
