### ISSUE TITLE
module directory name not consistent between centOS and Ubuntu

### ISSUE THREAD

**Issue by xpillons** [Azure/azhpc-images#120]
The module directory is not named the same between CentOS and Ubuntu images, avoiding the same MPI scripts to be used across platforms.

On CentOS : /usr/share/**Modules**/modulefiles/mpi/
On Ubuntu : /usr/share/**modules**/modulefiles/mpi

**Comment by LiquidPT** [comment]
yes, this continued when we moved to AlmaLinux from CentOS. It bothers me too, so I'll look into it.

**Comment by LiquidPT** [comment]
When I asked, I was told this was intentional. I'm not sure on the reason.
