### ISSUE TITLE
[OMAZUREMDS-8.4.0:ERROR] - centos 7 HPC image

### ISSUE THREAD

**Issue by tbugfinder** [Azure/azhpc-images#122]
Hello,

I'm starting my packer builds based on image "OpenLogic:CentOS7-HPC:7_9-gen2:latest".

Packer is started in debug mode so I can login in parallel.
/var/log/messages has loads of these messages, I'm not sure why those are rased and even azsec-monitor is installed although it should not be there.
```
<snip> rsyslogd: [0;31m[OMAZUREMDS-8.4.0:ERROR] <SetupConnectionWithMdsd>: error at connect(). socket_file='/var/run/mdsd/default_json.socket' errno=No such file or directory  [0m [v8.24.0-57.el7_9]
```
https://github.com/Azure/azhpc-images/blob/ee51461db34779b1054218cf2a9e11259b534309/centos/common/hpc-tuning.sh#L21

**Comment by abhamidipati0614** [comment]
### Steps to remove OMS agent from the VM
- Create the VM (image: OpenLogic:CentOS7-HPC:7_9-gen2:latest) using the tags --tags SkipASMAzSecPack=true SkipASMAV=true SkipLinuxAzSecPack=true (please refer https://developer.hashicorp.com/packer/plugins/builders/azure/arm#azure_tags for tag specification using packer)
- Delete the following packages from the VM. Use the command yum remove -y <packages-list>
    - azsec-monitor
    - azsec-clamav
    - auoms
    - azure-mdsd
    - azure-security
- Clear the /var/log/messages using rm -rf /var/log/messages
- Reboot the VM and verify
- Additionally, OMS agent can be removed from within the VM using the following:
    - wget https://raw.githubusercontent.com/microsoft/OMS-Agent-for-Linux/master/installer/scripts/uninstall.sh
    - chmod +x ./uninstall.sh
    - ./uninstall.sh
