### ISSUE TITLE
run_tests cannot be run as root

### ISSUE THREAD

**Issue by xpillons** [Azure/azhpc-images#14]
To run the test script you need to run with sudo, otherwise the lspci command is not found.
however when running with sudo mpirun failed because it runs as root :-)

mpirun has detected an attempt to run as root.

so either change the script call commands with sudo when they need to or add the right options to allow root to run mpirun (not the best one)

**Comment by jithinjosepkl** [comment]
>To run the test script you need to run with sudo, otherwise the lspci command is not found.
- isnt this a PATH issue in your environment? I haven't seen privileged access requirement for lspci.

**Comment by xpillons** [comment]
I'm building the VM with azhpc, calling the install script and then the run_tests.sh thru ssh.
VM is not rebooted after the install/
Dunno which path to use for lspci

**Comment by jithinjosepkl** [comment]
lspci should be available (/usr/sbin/lspci) even without running the install script. 
What's the OS here?

>VM is not rebooted after the install/
Maybe its not lspci that's failing for you, it could be the ibstat.
You need either a reboot or openibd restart before running the test script.
