### ISSUE TITLE
health_checks/NDv4/test-ib.sh not correct when AN is enabled

### ISSUE THREAD

**Issue by garvct** [Azure/azhpc-images#154]
On NDv4 with AN enabled, this test fails.

check ibstatus:
The minimum ib rate observed is 40, but it should be 200.
         **Fail** The settings returned by ibstatus indicate a problem.

Accelerated networking is not 200 gbits ?

**Comment by moes1** [comment]
Can you try with the latest version of the test (just from github)? That should be fixed now, unfortunately the version in our dsvm image is out of date. 

https://github.com/Azure/azhpc-images/blob/master/tests/health_checks/NDv4/test-ib.sh

**Comment by garvct** [comment]
Thanks, the new version gives the expected result.
