### ISSUE TITLE
VFs of mellonox MT27710 Family [ConnectX-4 Lx are going missing while listing them using ip link show but able to see them in lspci | grep bus address.

### ISSUE THREAD

**Issue by Saleem374** [Azure/azhpc-images#166]
Hi Team,

Please help me to get rid of this situation,

Where there are many servers with VFs inconsistency, some servers having 61, some are having 62, other with 63.

We have seen that this VFS are specifically fluctuating for only one PF i.e enp134s5 and missing VFs are enp134s5f5, enp134s5f6.

But those VFs enp134s5f5,enp134s5f6 are listing using lspci command. Please find the logs below

[root@overcloud-dl380vprobesriovperformancecompute-chc4b-c00-8 ~]# ethtool -i enp134s5                                                  
driver: mlx5_core
version: 5.0-2.1.8
firmware-version: 14.29.1016 (HP_2420110034)
expansion-rom-version:
bus-info: 0000:86:05.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: yes

Based on the bus-info when tried to check the partition information can see partition 5 and 6 pci address exists
[root@overcloud-dl380vprobesriovperformancecompute-chc4b-c00-8 ~]# lspci  |grep 86:05
86:05.0 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx Virtual Function]
86:05.1 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx Virtual Function]
86:05.2 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx Virtual Function]
86:05.3 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx Virtual Function]
86:05.4 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx Virtual Function]
86:05.5 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx Virtual Function]
86:05.6 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx Virtual Function]
86:05.7 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx Virtual Function]

And those VFs are not listed in ip link show command output,

logicalname: enp134s5   driverversion: 5.0-2.1.8
logicalname: enp134s5f1 driverversion: 5.0-2.1.8
logicalname: enp134s5f2 driverversion: 5.0-2.1.8
logicalname: enp134s5f3 driverversion: 5.0-2.1.8
logicalname: enp134s5f4 driverversion: 5.0-2.1.8
logicalname: enp134s5f7 driverversion: 5.0-2.1.8

Upon investigating we have found that those VFs are not existed, interesting thing is , if they are not created then why they are listed using lspci command.

[root@overcloud-dl380vprobesriovperformancecompute-chc4b-c00-8 ~]# ifconfig enp134s5f5
enp134s5f5: error fetching interface information: Device not found
[root@overcloud-dl380vprobesriovperformancecompute-chc4b-c00-8 ~]# ifconfig enp134s5f6
enp134s5f6: error fetching interface information: Device not found

Please help me to get an answer to this issue.

Thanks & Regards,Hi Team,

Please help me to get rid of this situation,

Where there are many servers with VFs inconsistency, some servers having 61, some are having 62, other with 63.

We have seen that this VFS are specifically fluctuating for only one PF i.e enp134s5 and missing VFs are enp134s5f5, enp134s5f6.

But those VFs enp134s5f5,enp134s5f6 are listing using lspci command. Please find the logs below

[root@overcloud-dl380vprobesriovperformancecompute-chc4b-c00-8 ~]# ethtool -i enp134s5                                                  
driver: mlx5_core
version: 5.0-2.1.8
firmware-version: 14.29.1016 (HP_2420110034)
expansion-rom-version:
bus-info: 0000:86:05.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: yes

Based on the bus-info when tried to check the partition information can see partition 5 and 6 pci address exists
[root@overcloud-dl380vprobesriovperformancecompute-chc4b-c00-8 ~]# lspci  |grep 86:05
86:05.0 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx Virtual Function]
86:05.1 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx Virtual Function]
86:05.2 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx Virtual Function]
86:05.3 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx Virtual Function]
86:05.4 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx Virtual Function]
86:05.5 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx Virtual Function]
86:05.6 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx Virtual Function]
86:05.7 Ethernet controller: Mellanox Technologies MT27710 Family [ConnectX-4 Lx Virtual Function]

And those VFs are not listed in ip link show command output,

logicalname: enp134s5   driverversion: 5.0-2.1.8
logicalname: enp134s5f1 driverversion: 5.0-2.1.8
logicalname: enp134s5f2 driverversion: 5.0-2.1.8
logicalname: enp134s5f3 driverversion: 5.0-2.1.8
logicalname: enp134s5f4 driverversion: 5.0-2.1.8
logicalname: enp134s5f7 driverversion: 5.0-2.1.8

Upon investigating we have found that those VFs are not existed, interesting thing is , if they are not created then why they are listed using lspci command.

[root@overcloud-dl380vprobesriovperformancecompute-chc4b-c00-8 ~]# ifconfig enp134s5f5
enp134s5f5: error fetching interface information: Device not found
[root@overcloud-dl380vprobesriovperformancecompute-chc4b-c00-8 ~]# ifconfig enp134s5f6
enp134s5f6: error fetching interface information: Device not found

Please help me to get an answer to this issue.

Thanks & Regards,
Saleemmalik,
+91-7815981336.
Saleemmalik,
+91-7815981336.

**Comment by jithinjosepkl** [comment]
Which SKU is this? Doesn't seem to be Azure HPC SKU.
