### ISSUE TITLE
Include HPC diagnostics on AlmaLinux HPC 8.6

### ISSUE THREAD

**Issue by NachoMtnz** [Azure/azhpc-images#200]
Please can you add the script to the image as in Ubuntu 20.04 hpc image? thanks!

**Comment by abhamidipati0614** [comment]
@NachoMtnz  The latest marketplace image with the URN almalinux:almalinux-hpc:8_6-hpc-gen2:8.6.2023041401 should have diagnostics installed at /opt/azurehpc/diagnostics/gather_azhpc_vm_diagnostics.sh
