### ISSUE TITLE
simplify the run-tests.sh

### ISSUE THREAD

**Issue by petersatsuse** [Azure/azhpc-images#210]
run-tests.sh has in the meantime a very complex structure and carrys many variables for the different distros and versions.

As the scripts write a the component versions in a file, this file could be used as a source for many of the variables used in run-tests.sh. Maybe it needs a bit closer look, but i think its worth the effort to make things more easy at the end

**Comment by abhamidipati0614** [comment]
This will be closed once Spack development is merged to master branch

**Comment by LiquidPT** [comment]
As a FYI, development using Spack was halted, but I will be working on porting simplified tests back to master
