### ISSUE TITLE
ibpanic after install in Ubuntu 20.04

### ISSUE THREAD

**Issue by ktaebum** [Azure/azhpc-images#213]
I installed the azhpc-images on
- Ubuntu 20.04
- Standard ND96amsr A100 v4 machine

with the latest commit ([c8db6de](https://github.com/Azure/azhpc-images/commit/c8db6de3328a691812e58ff56acb5c0661c4d488)).

However, when I run
```
$ ibstat
```
, it raises an error as
```
ibpanic: [769778] main: stat of IB device 'mlx5_an0' failed: No such file or directory
```

It seems the machine has `mlx5_ib0` to `mlx5_ib7`, why it tries to find `mlx5_an0`?

**Comment by jithinjosepkl** [comment]
mlx5_an0 is the Accelerated Networking (AN) interface (for front-end network), not IB, and ibstat does not support AN interface.
Please exclude the AN interface for ibstat, and run ibstat directly on the IB interfaces. (eg: ibstat mlx5_ib0).

Also, note that ibstatus works for AN interface also.
