### ISSUE TITLE
intelmpi 2021.8 module fails to load in a fresh batch environment on AlmaLinux-HPC 8.6 image

### ISSUE THREAD

**Issue by JonShelley** [Azure/azhpc-images#215]
[hpcuser@headnode 3cars]$ bash
bash-4.4$ module load mpi/impi_2021.8.0
Loading /opt/intel/oneapi/mpi/2021.8.0/modulefiles/mpi
  ERROR: Conflicting 'mpi' is loading

Loading mpi/impi_2021.8.0
  ERROR: Load of requirement '/opt/intel/oneapi/mpi/2021.8.0/modulefiles/mpi' failed

**Comment by abhamidipati0614** [comment]
@JonShelley Can you please share the image this is seen on?

**Comment by abhamidipati0614** [comment]
@JonShelley I am closing this one. Please re-open in case you need further information
