### ISSUE TITLE
CentOS-HPC 7.8 release date

### ISSUE THREAD

**Issue by tbugfinder** [Azure/azhpc-images#22]
Hello,

do you have any target date for the CentOS-HPC 7.8 image ?

Thanks & Best

**Comment by jithinjosepkl** [comment]
@tbugfinder - We don't have plans to release a 7.8 HPC image. Any specific reason that you are looking for this image?

**Comment by tbugfinder** [comment]
Hi, as discussed in #6 I have to use an updated kernel version. A kernel update requires reinstalling OFED drivers. I'm not sure about MPI libs, yet.
Therefore it would make sense providing a prebacked 7.8 HPC image.

**Comment by jithinjosepkl** [comment]
The issue described in #6 is fixed in kernel version 3.10.0-1062.12.1.el7.x86_64, and the latest CentOS 7.7 image is with that kernel version.

**Comment by tbugfinder** [comment]
Indeed I missed that. I rebuilt my image using 7.7 HPC and tested it successfully.
Out of curiosity why won't we see 7.8 HPC build?

**Comment by jithinjosepkl** [comment]
>I rebuilt my image using 7.7 HPC and tested it successfully.
That's good to know!

>Out of curiosity why won't we see 7.8 HPC build?
Mainly to reduce maintenance overheads. We want to focus on a small set of images and get them right. But, if there is a specific requirement for 7.8, we can always look into it.

(closing this issue)
