### ISSUE TITLE
Include Lustre client in all HPC images

### ISSUE THREAD

**Issue by blepore** [Azure/azhpc-images#23]
In an effort to provide a more cohesive story to our customers, we'd like to offer a Lustre client image. 

Maintaining this client and keeping it current with the Lustre server versions has been a historical painpoint for customers. Offering a HPC image with the Lustre client installed would be a huge plus for our customers. 

Below are some links on how to install the client. The DKMS link will be of particular interest for the Centos 7.x HPC Images. Whamcloud (current owner/maintainer of Lustre) do not offer RPMs for Centos 7.7 any longer. 

http://wiki.lustre.org/Installing_the_Lustre_Software#Lustre_Client_Software_Installation 
http://wiki.lustre.org/Installing_the_Lustre_Software#Using_DKMS

Our team is building its own client image for the time being for testing. We are using Ansible to do that. Below is a link to the playbook that we use for Centos images.

https://dev.azure.com/msazure/One/_git/Avere-laaso-dev?version=GBmaster&path=%2Fsrc%2Fansible%2Flclient.centos.playbook.yaml

The relevant snippet in that playbook is pasted below for convenience:
`    - name: remove /etc/yum.repos.d/lustre.repo
      become: true
      file:
        name: /etc/yum.repos.d/lustre.repo
        state: absent
    - name: generate /etc/yum.repos.d/lustre.repo
      become: true
      lineinfile:
        path: /etc/yum.repos.d/lustre.repo
        line: "{{ item }}"
        create: true
        owner: root
        group: root
        mode: 0o444
      with_items:
        - "[lustre-client]"
        - "name=lustre-client"
        - "baseurl={{ lustre_repo_centos_client }}"
        - "enabled=0"
        - "gpgcheck=0"
    - name: install Lustre CentOS DKMS packages
      become: true
      yum:
        enablerepo: lustre-client
        state: present
        update_cache: true
        name:
          - lustre-client-dkms
          - lustre-client
    - name: verify lustre install
      become: true
      when: true
      command: "modprobe -v lustre"`

**Comment by blepore** [comment]
We do have a DevOps dependency filed for this issue as well - https://msazure.visualstudio.com/One/_workitems/edit/7268596

**Comment by Klaas-** [comment]
Can you put the RPMs with the other microsoft built RPMs for CentOS/RHEL?
https://packages.microsoft.com/rhel/7/prod/

**Comment by abhamidipati0614** [comment]
The latest Ubuntu and AlmaLinux marketplace images come with Lustre client installed
