### ISSUE TITLE
amlfs-lustre-client-2.15.1-29-gbae0abe not found

### ISSUE THREAD

**Issue by githubtjl** [Azure/azhpc-images#295]
When I running at Ubuntu-20.04，
azhpc-images\ubuntu\commoninstall_lustre_client.sh:9
apt-get install -y amlfs-lustre-client-${LUSTRE_VERSION}=$(uname -r)
E: Version '5.16.0' for 'amlfs-lustre-client-2.15.1-29-gbae0abe' was not found

**Comment by LiquidPT** [comment]
The Ubuntu 20.04 HPC Image (including Lustre) is currently compatible with Linux Kernel 5.15.0-1037-azure. The latest LTS image (Canonical:0001-com-ubuntu-server-focal:20_04-lts-gen2:20.04.202310250) and daily image (Canonical:0001-com-ubuntu-server-focal-daily:20_04-daily-lts-gen2:20.04.202311270) are using kernel 5.15. 

It appears that you're using kernel 5.16. This configuration isn't supported.
