### ISSUE TITLE
GPG checks are failing on almalinux 8.7 image

### ISSUE THREAD

**Issue by aditigaur4** [Azure/azhpc-images#305]
Hello,

I am in the cyclecloud team and we do build slurm for almalinux 8.7. We are noticing that GPG checks have begun failing on RHEL's public repositories. This could be because almalinux is out of support for a while now. All the public keys that are listed in almalinux's website expired on jan 12 2024. I couldnt find a way to download public keys. 

I wanted to understand, if your team is still supporting almalinux or any other RHEL based distro. If so which one?

**Comment by N3WWN** [comment]
Perhaps this will help: https://almalinux.org/blog/2023-12-20-almalinux-8-key-update/

**Comment by aditigaur4** [comment]
> Perhaps this will help: https://almalinux.org/blog/2023-12-20-almalinux-8-key-update/

Thank you that fixed the issue!
