### ISSUE TITLE
install `nv_peer_mem` kernel for GPUDirect RDMA

### ISSUE THREAD

**Issue by ltalirz** [Azure/azhpc-images#316]
A customer on the Alma 8.7 image has run into

```
src/comm/transports/common/transport_ib_common.cpp:58: NULL value mem registration failed
src/comm/transports/ibrc/ibrc.cpp:486: non-zero status: 2 Unable to register memory handle.src/mem/mem.cpp:349: non-zero status: 7 transport get memhandle failed
src/mem/mem.cpp:604: non-zero status: 7 register heap handle failed
src/mem/mem.cpp:622: non-zero status: 7 add physical memory failed
src/comm/device/proxy_device.cu:701: NULL value failed allocating proxy_channel_g_bufchannel creation failed
```
with NVSHMEM and noticed that the `nv_peer_mem` kernel is missing.

```
$ lsmod | grep nv
nvidia_uvm           1376256  0
nvidia_drm             69632  0
nvidia_modeset       1245184  1 nvidia_drm
nvidia              56467456  106 nvidia_uvm,gdrdrv,nvidia_modeset
drm_kms_helper        176128  1 nvidia_drm
libnvdimm             200704  1 nfit
drm                   565248  4 drm_kms_helper,nvidia,nvidia_drm
```

See the docs https://docs.nvidia.com/nvshmem/api/faq.html

Would it make sense to add `nv_peer_memory` to the azhpc image?
https://github.com/Mellanox/nv_peer_memory

Anything we would need to watch out for?

mentioning also @xpillons

**Comment by jithinjosepkl** [comment]
Yes, nv_peer_mem should be added to Alma image as well. This can be fixed in the March release.

**Comment by LiquidPT** [comment]
I've tried this with the latest HPC AlmaLinux 8.7 image on an NDv4 VM, and nvidia_peermem is installed with the Mellanox driver and enabled. 

![image](https://github.com/Azure/azhpc-images/assets/10571341/7afd73e8-1f7d-4e05-877f-3980235f7795)

What version of the HPC AlmaLinux 8.7 image are you using and on which SKU?

**Comment by ltalirz** [comment]
Interesting, thanks for checking!

This was using the azhop image 2023.0705.1612, which derives from almalinux:almalinux-hpc:8_7-hpc-gen2:8.7.2023060101

@xpillons According to [the azhop docs](https://azure.github.io/az-hop/operate/marketplace_images.html), this is the latest base image for which azhop images are available. Perhaps worth looking into upgrading this?

Mentioning @matt-chan, @adam-grofe for info

**Comment by xpillons** [comment]
@ltalirz building new azhop image right now

**Comment by LiquidPT** [comment]
Closing as we're installing nvidia_peermem with the NVIDIA drivers on the current images
