### ISSUE TITLE
Feature request to add support for NCv5 

### ISSUE THREAD

**Issue by yosoyjay** [Azure/azhpc-images#332]
The current Ubuntu images do not include the NCCL topology file for the Standard_NC80adis_H100_v5 SKU.

**Comment by LiquidPT** [comment]
Will look into for the next release

**Comment by jithinjosepkl** [comment]
@yosoyjay , we don't need topo file for NCv5. NCCL detects the NVlink connectivity. Let us know if you hit any issues without the topo/graph files.
