### ISSUE TITLE
doc: how to build the image

### ISSUE THREAD

**Issue by tbugfinder** [Azure/azhpc-images#339]
Hello,

is there a guide available how to build images leveraging the repo within my own environment?

I'd assume packer and a specific order of given scripts.
Maybe I missed it, though.

thx

**Comment by LiquidPT** [comment]
I'll look at updating the docs, but at a high level its:

1. Create a VM and clone the repo
2. Navigate to the directory for the supported distro
3. run `sudo ./install.sh`
