### ISSUE TITLE
Enroot breaks in almalinux:almalinux-hpc:8_7-hpc-gen2:8.7.2024042601

### ISSUE THREAD

**Issue by xpillons** [Azure/azhpc-images#344]
User namespace is now disabled but required for enroot https://github.com/NVIDIA/enroot/blob/master/doc/requirements.md#kernel-settings
This is a breaking change for customers using enroot.

**Comment by darkwhite29** [comment]
@xpillons We are working on a fix and will update this thread when it's done. Thanks for your patience.

**Comment by xpillons** [comment]
[like]  Xavier Pillons reacted to your message:
________________________________

**Comment by darkwhite29** [comment]
@xpillons as you mentioned in the email, there are two suggested mitigation methods: we picked option 2 and you pointed it breaks AI workloads.

We thus try option 1, and unfortunately it doesn't work:  the `nf_tables` module cannot be disabled, as part of the firewall. We have to stick to adopting option 1 for now to have this security issue addressed.

Future AlmaLinux-HPC image will be using base images with security patch applied, and this issue will not be present: https://www.linuxquestions.org/questions/linux-software-2/problems-with-unloading-kernelmodule-rocky-linux-8-and-9-a-4175725602/

Sorry for the inconvenience and thanks for your understanding.

**Comment by xpillons** [comment]
Thank your for the analysis and testing, in the meantime waiting for the next release we have at least a workaround by reenabling Usernamespace.
