### ISSUE TITLE
leftover hello-world container in almalinux:almalinux-hpc:8_7-hpc-gen2:8.7.2024042601

### ISSUE THREAD

**Issue by xpillons** [Azure/azhpc-images#353]
this was supposed to be removed by PR #303 but it's not
![image](https://github.com/Azure/azhpc-images/assets/7349410/dca66782-c8a4-4a5a-9770-fbe79af0108f)

The exact command to run is `docker rmi hello-world` 
![image](https://github.com/Azure/azhpc-images/assets/7349410/d5553a74-6ad3-4d84-8073-1e673f57ea7e)

**Comment by LiquidPT** [comment]
This was fixed in PR #357
