### ISSUE TITLE
Any plan to support Ubuntu24.04

### ISSUE THREAD

**Issue by snowei** [Azure/azhpc-images#378]
Do we have any plan to support Ubuntu24.04, more specifically, HPC-X? Thanks.

**Comment by darkwhite29** [comment]
Yes, Ubuntu 24.04 is our next Ubuntu version to support, and HPC-X will be included. Thanks for your interest!

**Comment by snowei** [comment]
Thanks for your reply, is there any ETA?

**Comment by darkwhite29** [comment]
Scheduled to be January 2025, which may be delayed. Please check back later.

**Comment by themorey** [comment]
any update on the 24.04 release?  will there be a gen1 image or only gen 2?

**Comment by wttat** [comment]
hi @darkwhite29 , do we have any updates on this?

**Comment by darkwhite29** [comment]
ETA: Sept. 2025
