### ISSUE TITLE
Intel MKL in CentOS 8.1

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/azhpc-images#38]
Could you point me to the file that installs Intel MKL in CentOS-HPC:8.1 ?

I can't find the installation file referenced by
https://github.com/Azure/azhpc-images/blob/master/centos/centos-8.x/centos-8.1-hpc/install_intel_libs.sh

**Comment by anshuljainansja** [comment]
https://github.com/Azure/azhpc-images/blob/master/common/install_intel_libs.sh

**Comment by anshuljainansja** [comment]
Let me know if you have further questions.
I'll close the issue in 48Hrs.
