### ISSUE TITLE
Microsoft Azure email reporting that Almalinux-hpc 8.7 image is to be deprecated Dec 30th 2024?

### ISSUE THREAD

**Issue by garymansellricardo** [Azure/azhpc-images#386]
We are using AlmaLinux HPC 8.7 images for our CycleCloud cluster nodes in production and I received an email from Microsoft today that they are to be deprecated on Dec 30th 2024.

What are the future plans for an AlmaLinux 8 HPC VM image - will you release an 8.10 (current version) shortly that we can switch to using perhaps?

Alternatively, if you are to switch to AlmaLinux 9 - then we need to know about this urgently as I need to validate whether our HPC software applications will even run on AlmaLinux 9 (which might take significant time / be a problem if they don't).

Please can you urgently provide some information on your plans?

**Comment by darkwhite29** [comment]
AlmaLinux 8.7 image has a generalization issue and we replaced it with 8.10, which is currently available:

‘almalinux:almalinux-hpc:8_10-hpc-gen1:8.10.2024092301’
‘almalinux:almalinux-hpc:8_10-hpc-gen2:8.10.2024092301’

**Comment by garymansellricardo** [comment]
@darkwhite29  - thanks for getting back to me, I can see it (8.10) in the Marketplace - that's good.

So, I presume then that I need to speak with the CycleCloud team then, to get them to update CycleCloud to refer to this image rather than 8.7 (which the latest CycleCloud 8.6.4 version still refers to when you select "AlmaLinux8") - is that correct, or do you know if they already have this planned to be updated?

**Comment by garymansellricardo** [comment]
I don't think CycleCloud has been updated for the new AlmaLinux 8.10 HPC image that you have published.

I have just gone to  deployed a new Slurm Cluster and scheduler node on my 8.4.6 (fully updated CycleCloud Server) and it still comes as Alma Linux 8.7 HPC.:

![image](https://github.com/user-attachments/assets/0ae8ad72-86a7-4cec-8f95-11ab224e3d07)

Even when I check the Azure CycleCloud GitHub, for the latest slurm cluster template, it still refers to "almalinux8" - i.e. the same as the template on my current CycleCloud server, so I don't see how it would deploy AlmaLinux 8.10 (unless they update the CycleCloud application package to read "almalinux8" as AlmaLinux 8.10 HPC instead of AlmaLinux 8.7 HPC (as they do currently in the latest 8.4.6 version I have): 

![image](https://github.com/user-attachments/assets/6421ff5e-2700-4bfc-9ec5-2bff01c5f5fc)

I may be wrong - but it seems to me that they don't offer AlmaLinux 8.10 HPC image as an OOTB pick at this time?

**Comment by garymansellricardo** [comment]
No - it still creates AlmaLinux 8.7 nodes when you select AlmaLinux8 as the image:

![image](https://github.com/user-attachments/assets/2a1384e5-d55e-4623-99e8-fa9c27c41066)

I am running Azure CycleCloud Version: 8.6.4-3320 and creating a Slurm Cluster from the included default cluster template.

**Comment by darkwhite29** [comment]
Gary, thanks for you verification. Then yes, I think it's good to reflect this to CycleCloud team, asking them to, as you said, read "almalinux8" as AlmaLinux 8.10 HPC instead of AlmaLinux 8.7 HPC.

I'm not working on CycleCloud now. Do you have a contact to reach out to, or a way to report this issue with them? Thanks!

**Comment by garymansellricardo** [comment]
I have created this issue in their GitHub: https://github.com/Azure/cyclecloud-slurm/issues/282

But, I am not sure how pro-active they are with their issues, so if you know someone in the cyclecloud team, perhaps you could give them a nudge ;-)

**Comment by garymansellricardo** [comment]
It sounds like it's the CycleCloud team's issue not azhpc-images, so thanks very much for your help, I will close this issue

**Comment by darkwhite29** [comment]
@garymansellricardo Happy New Year! Quick question: do you mind sharing the Azure email you received back on Oct 1st? We have customers stating they haven't received such an email.

**Comment by garymansellricardo** [comment]
![Image](https://github.com/user-attachments/assets/ab0c954f-7630-4a8e-81da-cc0029186517)

**Comment by darkwhite29** [comment]
Great, thanks Gary!

**Comment by darkwhite29** [comment]
Hi @garymansellricardo,

We are tracking down who sent this email: are you able to share the rest of that email content, specifically the end of the communications that list the account information? I'll be able to confirm based on it. Thanks so much!

**Comment by garymansellricardo** [comment]
Not sure I understand - the Account Information at the bottom (that I deliberately did not include previously) only contains my Subscription Name and ID that I am not comfortable publishing, but if this helps:

![Image](https://github.com/user-attachments/assets/adfe5753-5f71-42c8-8000-403e5e81e14d)
