### ISSUE TITLE
support Rocky Linux builds

### ISSUE THREAD

**Issue by tbugfinder** [Azure/azhpc-images#39]
Hi,

with the EOL of CentOS8 end-of-2021 (https://blog.centos.org/2020/12/future-is-centos-stream/) as a build of RHEL8 sources and the raise of the Rocky Linux https://rockylinux.org community project, I'd to ask that this projects supports the successor.

Overall this might be a little early however we should be prepared for the change.

Thanks

**Comment by asklinux** [comment]
i have build vm on azure marketplace . this is Candidate version so use at your own risk

https://azuremarketplace.microsoft.com/en-us/marketplace/apps/tunnelbiz.rocky_linux?tab=Overview

**Comment by vermagit** [comment]
Hi @asklinux Could you provide details on what this VMI includes?

**Comment by asklinux** [comment]
> Hi @asklinux Could you provide details on what this VMI includes?

this image is min install for rocky linux .

**Comment by ltalirz** [comment]
Note also the AlmaLinux images https://github.com/Azure/azhpc-images/issues/121
Would be useful to know which of the two (if any) is picked as the CentOS successor

**Comment by ltalirz** [comment]
AlmaLinux seems now officially supported https://github.com/Azure/azhpc-images#readme

**Comment by abhamidipati0614** [comment]
There is no discussion on Rocky linux for now. AlmaLinux is chosen as CentOS successor.
