### ISSUE TITLE
CentOS-HPC 7.9 Image availability

### ISSUE THREAD

**Issue by tbugfinder** [Azure/azhpc-images#50]
Hi,

as CentOS 7.9 is the final and long-term CentOS7 release, I'm asking to also provide CentOS-HPC 7.9 image.

Q: Is this the correct project to ask about CentOS-HPC Images or is it rather the openlogic https://github.com/openlogic/AzureBuildCentOS repo?

**Comment by N3WWN** [comment]
Hi @tbugfinder !

Yes, this is the correct venue. 😃 

At https://github.com/openlogic/AzureBuildCentOS , we can only build the CentOS-HPC images for the CentOS versions that the https://github.com/Azure/azhpc-images project provides support for.

**Comment by vermagit** [comment]
@tbugfinder : Could you also provide your view on how you're looking at 7.9? Is it "long-term", or simply a short-term migration from 7.x to 7.9 while awaiting where the ecosystem moves to? In other words, would 7.9 be a replacement for other 7.x VMI for you?

**Comment by tbugfinder** [comment]
@vermagit 
We'll migrate onprem to 7.9 and would require 7.9 environment within Azure, too. Ideally cloud show be even ahead of onprem. As 7.9 is "supported" for several months, this is a mid-term :-) decision while we are indeed figuring out next major OS upgrade.
Personally, I'm in favour of rocky-linux 8.x.

**Comment by tbugfinder** [comment]
I'd like to add some emphasis to this request.
Any chance to get a pre-built HPC image?

**Comment by vermagit** [comment]
@tbugfinder We're considering the path ahead, and at the moment, it is aligned with yours as expressed above.
As a data point, where would you be migration from, to 7.9? In other words, could 7.9 be a substitute for 7.8, say?

**Comment by tbugfinder** [comment]
In our case 7.9 can certainly replace 7.8.

**Comment by tbugfinder** [comment]
Hi @anshuljainansja ,
your CentOS7.9 changes got integrated into the repo. Is it ready to build CentOS 7.9 Images?

FYI: @N3WWN

**Comment by vermagit** [comment]
@tbugfinder Indeed, we are now initiating working towards a 7.9 going forward.

**Comment by anshuljainansja** [comment]
@tbugfinder  @N3WWN 
I am testing the new ks file for Centos79-hpc. Will add the new ks file to the AzureBuildCentOS repo once done.

**Comment by tbugfinder** [comment]
Is there any estimated release date?

**Comment by vermagit** [comment]
ETA close to end of month right now due to some publishing delays.
Anyway, the docs will be updated: https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/hpc/configure#vm-sizes-supported-by-the-hpc-vm-images
and so will the linked blog post: https://techcommunity.microsoft.com/t5/azure-compute/azure-hpc-vm-images/ba-p/977094
