### ISSUE TITLE
Standard NC24rs_v3 - ib0 not available

### ISSUE THREAD

**Issue by tbugfinder** [Azure/azhpc-images#51]
Hello,

I've provisioned Standard NC24rs_v3 using CentOS-HPC 7.7 and 7.8.
In either case ib0 isn't configured properly and isn't available.

Is there an issue with the OFED installation?

```
# lspci
0001:00:00.0 3D controller: NVIDIA Corporation GV100GL [Tesla V100 PCIe 16GB] (rev a1)
0002:00:00.0 3D controller: NVIDIA Corporation GV100GL [Tesla V100 PCIe 16GB] (rev a1)
0003:00:00.0 3D controller: NVIDIA Corporation GV100GL [Tesla V100 PCIe 16GB] (rev a1)
0004:00:00.0 3D controller: NVIDIA Corporation GV100GL [Tesla V100 PCIe 16GB] (rev a1)
86fc:00:02.0 Network controller: Mellanox Technologies MT27500/MT27520 Family [ConnectX-3/ConnectX-3 Pro Virtual Function]
```
ib0 isn't configured at all.
and ibstatus errors out:
```
ibstatus
Fatal error:  device '*': sys files not found (/sys/class/infiniband/*/ports)
```

```
uname -a
Linux pkrvm226m165fgz 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

So I decided to install MLNX OFED and perform a reboot.
After that ib0 is configured - it looks like the Mellanox adapter is used for IB and ethernet though.

```
4: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    link/infiniband a0:00:6c:20:fe:80:00:00:00:00:00:00:00:15:5d:ff:fd:33:ff:24 brd 00:ff:ff:ff:ff:12:40:1b:80:06:00:00:00:00:00:00:ff:ff:ff:ff
    inet 172.16.1.27/16 brd 172.16.255.255 scope global ib0
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fd33:ff24/64 scope link
       valid_lft forever preferred_lft forever

```

**Comment by tbugfinder** [comment]
Ok, so turns out I have to use an older base image.
That's somehow confusing.

**Comment by vermagit** [comment]
For the record, adding the [MOFED support matrix](https://www.mellanox.com/support/mlnx-ofed-matrix?mtag=linux_sw_drivers) and [documentation ](https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/hpc/configure#sr-iov-enabled-vms)on using MOFED<=5.0 for CX3-Pro IB NIC.
